data_optimal <- read.table("loss_output_optimal/lossvalue.tbl", sep = " ")
data_greedy <- read.table("loss_output_greedy/lossvalue.tbl", sep = " ")
data_proportional <- read.table("loss_output_proportional/lossvalue.tbl", sep = " ")
jpeg("rplot.jpg")
plot(data_optimal[,1], data_optimal[,2], type = "n", col = "red")
lines(data_optimal[,1], data_optimal[,2], type = "l", col = "red")
lines(data_greedy[,1], data_greedy[,2], type = "l", col = "green")
lines(data_proportional[,1], data_proportional[,2], type = "l", col = "blue")
legend("topright", inset = .05, cex = 1, title = "", c("Optimal", "Greedy", "Proportional"), horiz = TRUE, lty = c(1, 1), lwd = c(2, 2), col = c("red", "green", "blue"))
dev.off()
